geofileops/geofileops.py, geofileops/util/geofileops_sql.py, tests/test_geofileops_sql_twolayers.py
=> Improve placeholder used for the input layer name in sql statements

geofileops/util/geofileops_sql.py, tests/test_geofileops_sql_twolayers.py
=> Bugfix: explodecollections not working on operations on 2 layers + add test

geofileops/util/geofileops_sql.py, geofileops/util/sqlite_util.py, tests/test_geofileops_sql_twolayers.py
=> Some bugfixes

geofileops/util/geofileops_sql.py
=> Reduce memory usage for large input in 2 layer operations

geofileops/geofile.py, geofileops/util/general_util.py, geofileops/util/geofileops_gpd.py, geofileops/util/geofileops_sql.py, geofileops/util/ogr_util.py, geofileops/util/sampledata_util.py, tests/test_geofile.py, tests/test_geofileops_gpd.py, tests/test_vector_util_geometry.py
This prevents the computer from becoming slow for other tasks while running an operation on large input files.
Closes #25
=> Run processing in lower process priority

bin/create_env/geofileops.sh, ci/envs/38-latest-conda-forge.yaml, ci/envs/39-latest-conda-forge.yaml, environment.yml, geofileops/geofileops.py, geofileops/util/geofileops_gpd.py, geofileops/util/ogr_util.py, setup.py, tests/test_geofile.py, tests/test_geofileops_gpd.py, tests/test_helper.py, tests/test_vector_util_geometry.py, tests/test_vector_util_geoseries.py
=> Add operation apply

geofileops/geofileops.py, geofileops/util/geofileops_gpd.py, tests/test_geofileops_gpd.py
=> Add apply operation - Improve and fix tests

geofileops/util/_geoops_gpd.py, geofileops/util/general_util.py
=> Make progress reporting more consistent + fix seconds

benchmark/benchmarker.py, benchmark/benchmarks/benchmarks_geofileops.py, benchmark/benchmarks/testdata.py
- prepare to add more test files
- replace package and version by private functions
- skip functions starting with "_" when benchmarking
=> Small improvements to benchmark

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_gpd.py, tests/test_geofileops_singlelayer_gpd.py
using `from datetime import datetime` makes a lot of lines of code more readable...  
Related to #95
=> Remove deprecated clip on tiles parameter in dissolve + import datetime.datetime

geofileops/fileops.py, tests/test_geofile.py
- option to specify dialect to use for the expression
- better error handling
- accept extra data types as input
=> Improvements to add_column

.github/workflows/tests.yml
To (try to) improve performance of running tests
Reference #106
=> Use mambaforge for CI tests

CHANGELOG.md, geofileops/fileops.py
Some changes that still needed to be committed...
=> List/write attribute tables - Small improvements

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, geofileops/util/_ogr_util.py, samples/GIS_analysis.py
=> Remove verbose parameter everywhere

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_ogr.py, geofileops/util/_ogr_util.py, tests/test_geofileops_singlelayer_ogr.py
followup on #144 
closes #149, #150, #151
=> Finalize new single-layer spatial functions warp, clip_by_geometry, export_by_bounds

bin/create_env/geofileops.sh, ci/envs/38-latest-conda-forge.yaml, ci/envs/39-latest-conda-forge.yaml, environment.yml, geofileops/fileops.py, geofileops/util/geofiletype.py, geofileops/util/geofiletypes.csv, setup.py, tests/test_geofile.py, tests/test_geofileops_twolayers.py, tests/test_helper.py
Found some bugs in pyogrio that are blocking + found the reason geopandas 11 + fiona gave issues (#153), so easiest to roll back
=> Revert using pyogrio for io

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_general_util.py, geofileops/util/_geoops_gpd.py, tests/test_geofileops_singlelayer_gpd.py
=> Fix groupby columns in dissolve not being treated case insensitive

geofileops/fileops.py, tests/test_geofile.py
=> Fix: to_file doesn't throw error nor saves data to output file if dataframe has different columns

CHANGELOG.md, geofileops/util/_general_util.py, geofileops/util/_geoops_gpd.py
=> Fix ValueError: max_workers must be <= 61 in dissolve

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_sql.py
=> Fix support for sql_dialect parameter in select operation

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_gpd.py, tests/test_geofileops_singlelayer_gpd.py
=> Fix for groupby columns becoming null in dissolve

CHANGELOG.md, geofileops/util/_geoops_gpd.py
Mainly a (big) improvement when there are a lot of tiles and/or the CPU need for processing (unioning) is small.
=> Improve dissolve performance

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_geoops_sql.py, geofileops/util/_ogr_util.py, tests/test_geofileops_singlelayer.py, tests/test_geofileops_singlelayer_sql.py
Not really important things, but some tests failed because of different (better) handling in gdal of some edge cases when executing SQLITE sql statements on gpkg and shp.
=> Fixes for compatibility with gdal 3.6.2

geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py, tests/test_spatialite.py
- Some extra comments
- An extra test
=> Small improvements

CHANGELOG.md, geofileops/util/_geoops_sql.py
Determining the min_rowid and max_rowid took quite some time for large input files. Writing the SQL query slightly different solved this.
=> Improve performance of sql-based operations for very large input files

geofileops/util/_ogr_util.py, tests/test_ogr_util.py
=> Remove some old deprecated code in ogr_util

CHANGELOG.md, geofileops/fileops.py, tests/test_geofile.py
=> Add support for sql_stmt param in read_file

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, geofileops/util/_ogr_sql_util.py, tests/test_geofile.py, tests/test_geofileops_singlelayer.py, tests/test_geofileops_singlelayer_gpd.py, tests/test_geofileops_singlelayer_sql.py, tests/test_geofileops_twolayers.py, tests/test_ogr_sql_util.py
Now, the casing as in the input file is used.
=> Use casing in columns param in read file for the output dataframe

CHANGELOG.md, docs/reference.rst, geofileops/fileops.py, tests/test_geofile.py
=> Add function get_layer_geometrytypes to get all actual geometry types present in a layer.

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_gpd.py, tests/test_geofileops_singlelayer_gpd.py
+ fix regression for amongst others apply in _geoops_gpd._apply_geooperation() introduced in #190 -> fixes #231
=> Add force_output_geometrytype parameter to gfo.apply

CHANGELOG.md, geofileops/util/_geoops_sql.py, tests/test_geofileops_singlelayer_sql.py, tests/test_geofileops_twolayers.py
=> Check in select ops that if nb_parallel > 1, {batch_filter} placeholder is mandatory

geofileops/util/_sqlite_util.py
=> Remove unused functions execute_select_sql and execute_select_sql_df

geofileops/util/_sqlite_util.py
=> Remove unused function execute_sql

geofileops/util/_io_util.py, tests/test_io_util.py
=> Remove obsolete functions copyfile and is_locked

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, tests/test_geofile.py, tests/test_geofileops_singlelayer.py, tests/test_geofileops_singlelayer_gpd.py, tests/test_geofileops_twolayers.py
=> Add checks that output_path must not be equal to the/an input_path

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/test_geofileops_singlelayer_sql.py
=> Speed up makevalid and isvalid

tests/test_geofile.py
=> Add test for combination of layerstyle and rename_layer

CHANGELOG.md, geofileops/_compat.py, geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/test_geofileops_singlelayer_sql.py, tests/test_geoseries_util.py
gridsize is the term used in most libraries: geos, shapely, spatialite, postgis,...
=> Rename makevalid parameter precision to gridsize + add tests

geofileops/util/_geoops_sql.py, tests/test_geofileops_singlelayer_sql.py, tests/test_geofileops_twolayers.py
=> Avoid errors being obfuscated by rmtree cleanup errors

CHANGELOG.md, geofileops/fileops.py, tests/test_geofile.py
=> Fix-parameter-index-in-to_file-is-ignored + add test

tests/test_geofileops_singlelayer_gpd.py
=> Backport-to-0.7.x-fix-tests-for-concat-order-is-not-guaranteed

CHANGELOG.md, ci/envs/310-latest-conda-forge.yaml, ci/envs/311-latest-conda-forge.yaml, ci/envs/38-latest-conda-forge.yaml, ci/envs/39-latest-conda-forge.yaml, ci/envs/readthedocs.yml, environment-dev.yml, geofileops/__init__.py, geofileops/util/geometry_util.py, geofileops/util/geoseries_util.py, setup.py, tests/test_helper.py
Geofilops now follows the behaviour of geopandas to either use shapely2 or pygeos depending on availability and/or configuration using environment variable USE_PYGEOS.
Closes  #294
=> Follow geopandas behaviour of using shapely2 and/or pygeos

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_ogr_util.py, tests/test_geofile.py, tests/test_ogr_util.py
=> Add where parameter to convert and append_to

geofileops/util/geometry_util.py, tests/test_geometry_util.py
=> Add GeometryType.to_singletype

CHANGELOG.md, geofileops/util/_ogr_util.py, tests/test_ogr_util.py
Catch some extra cases where a "geom" or "geometry" TEXT column was created if the first rows "geometry"/"geom" column returned NULL geometries.
=> Improve handling of empty input layers/NULL geometries

.gitignore, .pre-commit-config.yaml, CHANGELOG.md, benchmark/benchmarker.py, benchmark/benchmarks/benchmarks_geofileops.py, benchmark/benchmarks/testdata.py, benchmark/reporter.py, docs/conf.py, environment-dev.yml, geofileops/__init__.py, geofileops/fileops.py, geofileops/geoops.py, geofileops/helpers/layerstyles.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, geofileops/util/_ogr_util.py, geofileops/util/geometry_util.py, geofileops/util/geoseries_util.py, geofileops/util/grid_util.py, pyproject.toml, setup.cfg, tests/test_geofile.py, tests/test_geofileops_singlelayer_gpd.py, tests/test_geofileops_singlelayer_sql.py, tests/test_geofileops_twolayers.py, tests/test_geometry_util.py, tests/test_geoseries_util.py, tests/test_helper.py
=> Use ruff instead of flake8

geofileops/geoops.py, geofileops/util/_io_util.py, geofileops/util/_processing_util.py, geofileops/util/_sqlite_util.py
Use # pragma: no cover on lines/code paths that don't need code coverage.
=> Ignore some lines that don't need test coverage

CHANGELOG.md, geofileops/util/_sqlite_util.py, tests/test_geofileops_twolayers.py
Fix: fid column is detected as NUMERIC and was incorrectly interpreted as DATETIME.
Might also fix cases for other columns...
=> Fix fid column having null values in e.g. union

CHANGELOG.md, geofileops/util/_geoops_sql.py
Add LIMIT -1 OFFSET 0 on some places to avoid subquery flattening.
=> Improve performance for single layer operations

.env, CHANGELOG.md, geofileops/fileops.py, geofileops/geoops.py, geofileops/util/_geoops_sql.py, geofileops/util/_sqlite_util.py, tests/test_geofile.py, tests/test_geofileops_twolayers.py, tests/test_spatialite.py, tests/test_sqlite_util.py
=> Add support to use select_two_layers on non geo files

geofileops/util/_geoops_sql.py, tests/test_geoops_sql.py
- round up to multiples of nb_parallel in some extra cases.
=> Improve determination of number of batches

CHANGELOG.md, geofileops/geoops.py
I change my mind: default behaviour of removing NULL geometry rows has advantages as well, so not worth the trouble of changing the default.
=> Remove warning that parameter keep_empty_geoms default value is going to change

CHANGELOG.md, ci/envs/latest.yml, ci/envs/minimal.yml, ci/envs/readthedocs.yml, environment-dev.yml, geofileops/fileops.py, geofileops/util/_ogr_util.py, setup.py, tests/test_geofile.py, tests/test_geofileops_singlelayer.py, tests/test_helper.py
=> Add support for files with Z/M dimensions in the general file and layer operations

geofileops/util/_geoops_sql.py
=> Use spatialite 5.1 functions for makevalid when possible

ci/envs/latest.yml, ci/envs/minimal.yml, ci/envs/readthedocs.yml, environment-dev.yml, geofileops/_compat.py, geofileops/geoops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, geofileops/util/_geoseries_util.py, geofileops/util/_ogr_util.py, geofileops/util/_sqlite_userdefined.py, geofileops/util/_sqlite_util.py, setup.py, tests/test_geofileops_singlelayer.py, tests/test_geoseries_util.py, tests/test_helper.py, tests/test_spatialite.py
TODO:
- Depends on https://github.com/conda-forge/libspatialite-feedstock/pull/101
- Add test on spatialite version to choose the old or new implementation
Resolves #401
Resolves #354
=> Improve handling of invalid geoms with gridsize in single layer sql operations

geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/test_geofile.py, tests/test_geofileops_singlelayer.py
Not mentioned in the changelog, as the bug was introduced in an unreleased version.
=> Fix unique constrained violated on fid for single layer sql operation on .shp to .gpkg

geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, geofileops/util/_ogr_util.py, tests/test_geofileops_singlelayer.py, tests/test_geofileops_twolayers.py, tests/test_helper.py
Not mentioned in the changelog, as the bug was introduced in an unreleased version.
Take in account explodecollections in several extra operations.
=> Fix unique constrained violated on fid on .shp to .gpkg part 2

geofileops/fileops.py, geofileops/util/_geoops_sql.py
PR #434 adds an extra property to the public ColumnInfo class, but this is not strictly necessary, so better don't do so.
=> Rollback unnecessary change in PR #434

docs/user_guide.rst, geofileops/fileops.py, geofileops/geoops.py
General improvements and some fixes to documentation.
=> Several improvements to DOC

CHANGELOG.md, geofileops/util/_geoops_gpd.py, tests/test_geofileops_singlelayer_gpd.py
Small change to this fix... simplify code
=> Fix dissolve error when pass that isn't last one has 0 polygons in onborder resultv - simplification

geofileops/geoops.py, tests/test_geofile.py, tests/test_geofileops_singlelayer_gpd.py, tests/test_geofileops_singlelayer_ogr.py, tests/test_geofileops_twolayers.py, tests/test_geoops.py
Was not yet supported and/or the type was not correctly annotated for:
- warp
- dissolve_within_distance
- union
=> ENH: support str input paths for some extra functions + add tests

README.md, docs/index.rst
or something like that, so it can be seen straight away?
=> DOC: Specify benchmark dataset size in readme and index.rst

docs/faq.rst, docs/index.rst, docs/user_guide.rst
=> DOC: add tip to use __main__ block in standalone scripts

CHANGELOG.md, geofileops/util/_geoops_sql.py
=> BUG: fix wrong results returned by join by location if ran on result of join by location

.pre-commit-config.yaml, CHANGELOG.md, docs/development.rst, environment-dev.yml, geofileops/fileops.py, geofileops/util/_geoops_gpd.py, pyproject.toml
=> ENH: use ruff-format instead of black

CHANGELOG.md, docs/faq.rst, docs/reference.rst, geofileops/fileops.py, geofileops/geoops.py, geofileops/helpers/_configoptions_helper.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, geofileops/util/_sqlite_util.py, tests/test_configoptions_helper.py
Can be used to avoid temp files being removed for debugging purposes.
=> ENH: Add configuration option GFO_REMOVE_TEMP_FILES

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
=> ENH: improve handling of disjoint queries in join_by_location

CHANGELOG.md, geofileops/util/_geoops_sql.py, tests/test_geoops_sql.py
=> ENH: don't copy both input files if only one is not spatialite based

geofileops/util/_geoops_sql.py, tests/test_geofileops_singlelayer_sql.py
=> ENH: add test to document deduplication of column names

tests/test_geofileops_singlelayer_ogr.py, tests/test_geofileops_twolayers.py
xfail the failing tests, as there isn't a proper fix...
=> CI: xfail failing tests on MacOS on arm64

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, geofileops/util/_ogr_util.py, tests/test_geofile.py, tests/test_geofileops_singlelayer.py, tests/test_geofileops_twolayers.py, tests/test_geoops_dissolve.py, tests/test_ogr_util.py
=> ENH: improve handling of string passed for columns parameter

CHANGELOG.md, ci/envs/minimal.yml, geofileops/geoops.py, geofileops/util/_geoops_sql.py, geofileops/util/_sqlite_userdefined.py, geofileops/util/_sqlite_util.py, setup.py, tests/test_geofileops_twolayers.py, tests/test_geoops_sql.py, tests/test_helper.py
=> ENH: improve performance of erase for very complex input geometries 

CHANGELOG.md, docs/reference.rst, geofileops/geoops.py, geofileops/util/_geoops_gpd.py, tests/test_geofileops_singlelayer_gpd.py
=> ENH: add a vectorized version of apply

CHANGELOG.md, geofileops/util/_geoops_sql.py
Use options introduced here: #588
=> ENH: use apply_vectorized internally where possible

CHANGELOG.md, README.md, ci/envs/latest-fiona.yml, docs/reference.rst, docs/user_guide.rst, geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
To use same terminology as most other open source projects...
=> ENH: rename erase to difference

CHANGELOG.md, docs/index.rst, docs/installation.rst, geofileops/_compat.py, geofileops/util/_general_util.py, geofileops/util/_ogr_util.py, geofileops/util/_sqlite_util.py
=> ENH: add some pre-flight checks when geofileops is imported

CHANGELOG.md, geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
=> ENH: only apply subdivide once on each input layer in symmetric_difference

geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
=> ENH: only apply subdivide once on each input layer in identity

tests/test_geofileops_twolayers.py
adressing #303
I would be glad to get some feedback. If this meets your expectations, I could write more unit test if needed.
=> TST: Improve test test_export_by_distance

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_ogr.py, geofileops/util/_geoops_sql.py, tests/test_geofile.py, tests/test_geofileops_singlelayer_gpd.py, tests/test_geoops_sql.py, tests/test_spatialite.py
Speed up by reducing the number of gdal.OpenEx calls.
Closes #622
=> TST: Speed up processing many small files

.github/workflows/perftests.yml, .github/workflows/tests.yml, perftests/test_many_small_files.py, pyproject.toml
=> TST: some performance tests in context of processing many small files [skip Tests]

geofileops/util/_sqlite_util.py
Recently the windows CI tests started crashing regularly. The crashes seem to be happening in `sqlite_util.create_spatialdb`, but the crash happens on different moments in different tests, so it is not consistent.
The only recent change in the function is to use  `executescript` instead of `execute`, not sure how this would lead to occasional crashes in this function, but his PR rolls back this change hoping it makes the function/tests stable again.
=> BUG: rollback using executescripts in create_spatialdb

CHANGELOG.md, docs/user_guide.rst, geofileops/fileops.py, geofileops/geoops.py, geofileops/util/_geoops_gpd.py
In this PR::
- Several small improvements and fixes
- Add "See Also" sections for relevant functions
- Expand the user manual
- Add some more examples to some functions
=> DOC: improvements and fixes

geofileops/util/_geoops_sql.py
=> ENH: add missing optimisation to symmetric_difference

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, tests/test_geofile.py
=> BUG: the default dst_layer in copy_layer and append_to is not the stem of the filename

geofileops/geoops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py
Some small improvements to avoid having warnings in the tests...
=> ENH: small improvements to avoid warnings being reported in tests

geofileops/fileops.py
Adding and updating a column can take some time, so nicer if there is (progress) logging.
=> ENH: add info logging in add and update_column

CHANGELOG.md, benchmark/benchmark_geofileops.py, benchmark/benchmarks/benchmarks_geofileops.py, geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/two_layer_operations/test_geofileops_twolayers.py
This PR includes:
- Subdividing the clip layer if it is complex.
- Add test
- Add benchmark
Remark: the input_layer isn't subdivided being yet, so a complex input layer can still be slow.
=> ENH: Improve performance of clip with a complex clip layer

CHANGELOG.md, docs/reference.rst, geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/multi_layer_operations/test_join.py
=> ENH: add join function
