CHANGELOG.md, benchmark/benchmarks/benchmarks_geofileops.py, docs/user_guide.rst, geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
Deprecate `gfo.intersect()` for new name `gfo.intersection()` to be consistent with most other libraries. Now a warning is given, in the future `gfo.intersect()` will be removed.
=> Deprecate intersect and rename to intersection

ci/envs/38-latest-conda-forge.yaml, ci/envs/39-latest-conda-forge.yaml, setup.py
Some packages are imported/used directly in geofileops, but they are only installed because another package used in geofileops has a dependency on them. 
So, if this other package would remove the dependency, geofileops breaks.
So, all packages that are used directly should be explicitly mentioned in the dependencies. 
Related to #101
=> Add all direct dependencies of geofileops explicitly in setup.py + ci environments

geofileops/util/_geoops_sql.py, geofileops/util/geoseries_util.py
Now in the sql functions simplify without preserve is used (the default there), in paths that use geopandas with preservetopology (the default).
Make it consistent that preserve topology is always applied/tried.
=> Always use simplify that preserves topology

geofileops/util/_general_util.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py
Improves performance of processing the (small: ~50 rows) test files with a factor 2).
This PR changes that input files <= 100 rows are processed in threads, but this is purely based on the size of the test files. Would be better to test a bit more to choose the number better + possibly difference on Linux vs. Windows
References #106
=> Process small files in Threads instead of in processen

tests/test_geofile.py
Apparently, when the geometry column is dropped the GeoDataFrame now (correctly) becomes a DataFrame automatically.
=> Update test to support new pandas versions

setup.py
It is optional, but seems just easier to install it by default to avoid hassle.
=> Add simplification as install requirement

.github/workflows/tests.yml, ci/envs/311-latest-conda-forge.yaml
simplification lib is now available for python 3.11
=> Activate simplification in ci of python 3.11

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_io_util.py, geofileops/util/_ogr_util.py, tests/test_geofile.py, tests/test_geofileops_twolayers.py
- On a k8 cluster, for a volume mounted via cifs there seem issues that gpkg files remain locked. When add_column is ran after eg. the export_by_location operation this error is raised: database is locked. The lock is gone when the script ends, so might be an issue that locks are "delayed" in getting cleared? Not able to reproduce in a dev environment.
- solution tried: remove custom implementation for copy-file in gfo.move() as it apparently isn't faster anymore. 
- On windows, when appending to a gpkg file, "attempt to write a readonly database" occurs sometimes (on a network location). Mark that there is already a locking mechanism using lock files in place in to_file().
- solution: use retry mechanism also if geopackage is locked
=> Make writing to gpkg more robust in locking situations

.github/workflows/tests.yml, CHANGELOG.md, ci/envs/39-latest-conda-forge-shapely1.yaml, geofileops/__init__.py, geofileops/util/_geoops_gpd.py, geofileops/util/geoseries_util.py, geofileopsdev.yml, tests/test_geofile.py, tests/test_geofileops_singlelayer_gpd.py, tests/test_geoseries_util.py
- Some code changes to support the changed behaviour as explained here: https://shapely.readthedocs.io/en/latest/migration.html#consistent-creation-of-empty-geometries
- Should be backwards compatible, so shapely < 2 should still work as well.
- pygeos is still used for spatial operations because once full change to shapely 2.0 is activated it isn't possibly anymore (according to the documentation) to use pygeos? -> to be further investigated.
- _ogr_util.vector_info was used in the dissolve operation to create an attribute index, but this now gives a segmentation fault on MacOS/Darwin. Using gfo.execute_sql instead solved the problem.
=> Support geopandas 12 with shapely 2.0 + pygeos

CHANGELOG.md, geofileops/fileops.py, setup.py, tests/test_geofileops_singlelayer_gpd.py
When reading empty data from a column in a gpkg, Fiona doesn't offer the distinction anymore between None (string) and nan (real/numeric) columns starting from version 1.9, resulting in GeoPandas interpreting them as float64 columns instead of object columns.
This fix converts these columns to "object" type after reading.
Closes #199
=> Using read_file, string columns with all None values ends up as float64 column using fiona >= 1.9

benchmark/benchmark_geofileops.py, geofileops/util/_geoops_sql.py
Where there is only one batch, only one temp partial file, so can be renamed instead of appended.
related to #19
=> Optimize performance of single layer sql operations when nb_parallel = 1

geofileops/fileops.py, geofileops/util/_geoops_ogr.py, geofileops/util/_geoops_sql.py, tests/test_geofileops_singlelayer.py, tests/test_geofileops_singlelayer_gpd.py, tests/test_geofileops_singlelayer_ogr.py, tests/test_geofileops_twolayers.py
Problem was introduced in #213 
Additional change: create spatial index for shp in all spatial operations: behaviour was different for each operation
=> Fix spatial index not being created in two-layer operation with nb_parallel=1

geofileops/fileops.py, geofileops/util/_geoops_sql.py, geofileops/util/_sqlite_util.py
The gdal SQLITE function `CreateSpatialIndex()` didn't work on files created by `_sqlite_util.create_table_as_sql`. Problem was apparently that the fid column wasn't present:
- added the fid column
- added `preserve_fid=False` to the append() call that appends these files, because the default gdal behaviour apparently lead to it trying to insert duplicate fid's.
- removed the obsololete (and not really working) code trying to recover the problem in `fileops.create_spatial_index()`
=> Fix missing fid in gpkg created with create table as sql

tests/test_geofileops_singlelayer_gpd.py
In some tests the results of e.g. concatted grouped values wasn't sorted before comparison, and the order of those values isn't guaranteed...
=> Fix dissolve tests: order of values is not guaranteed in concatted groupby results

geofileops/helpers/layerstyles.py, tests/data/polygonstyle.qml, tests/data/polygonstyle.sld
Uses bind variables now to avoid these kind of issues...
reference #263
=> Fix error in add_layerstyle if qml contains single quote

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_geoops_sql.py, tests/test_geofile.py, tests/test_helper.py, tests/test_layerstyles.py
Deprecate the old name that stays available for backwards compatibility.
closes #310
=> Rename convert to copy_layer

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_geoops_sql.py, geofileops/util/geofiletypes.csv, tests/test_geofile.py, tests/test_geofileops_singlelayer_sql.py
Now, if you use `gfo.select` on an input file without geometry column or if you don't select a geometry column in you sql_stmt this leads to an error.
This PR adds support for both cases.
Remark: a shapefile without geometry column is in fact only a .dbf file: both .shp and .shx files are missing.
=> Support creating geofile without geometry column using gfo.select

CHANGELOG.md, geofileops/util/_geoops_sql.py
Improvements:
- The WITH statement with GROUP BY is removed, which reduces the the memory usage for large files by > 10x
- The difference part of the query is replaced by the optimized functions from the `erase` operation
TODO: the intersection part can still be optimized for complex geometries, the following issue has been registered for this: #332
=> Improve performance/memory usage of `split`, especially for files with very large input geometries

geofileops/util/_sqlite_util.py, tests/test_sqlite_util.py
Some triggeres were removed from the gpkg spec because of issues but apparently weren't removed in spatialite function "SELECT gpkgCreateBaseTables();".
Triggers involved
https://github.com/opengeospatial/geopackage/pull/240
Fix: drop them after using `gpkgCreateBaseTables`.
=> Fix trigger error with drop_column for some gpkg files

geofileops/util/_geoops_sql.py
The "LIMIT -1 OFFSET 0 " meant to avoid the subquery flattening was placed after the outer query instead of in the subquery... so didn't do a lot...
=> Fix placement of LIMIT OFFSET clauses for gridsize and where subselects

CHANGELOG.md, benchmark/benchmark_geofileops.py, geofileops/util/_geoops_sql.py
Add some `LIMIT -1 OFFSET 0` in sql statements of `clip`and ìntersection` to improve execution plan and avoid executing expesive geo operations twice.
=> Improve performance for clip and intersection

CHANGELOG.md, geofileops/fileops.py, geofileops/geoops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, tests/test_geofile.py, tests/test_geofileops_singlelayer.py, tests/test_geofileops_singlelayer_ogr.py, tests/test_geofileops_singlelayer_sql.py
fid's are preserved in gpkg output files if explodecollections is False.
=> Preserve fid values when possible in single layer operations

.github/workflows/tests.yml, CHANGELOG.md, ci/envs/latest.yml, ci/envs/minimal.yml, ci/envs/readthedocs.yml, environment-dev.yml
Following main changes:
* `geopandas` -> `geopandas-base`
* once tests are OK -> conda feedstock can be changed.
* `pygeoops`: use release (conda) version again 
* use `nomkl` for linux builds:
* if specified in the depencencies, it avoids the mkl numerical library to be used by numpy, which is huge. Instead openblas will be installed.
* for the linux builds this works fine, but running the tests on MacOS and Windows takes double te time.
* Conclusion: only for linux!
=> TST: Use smaller conda dependency packages where possible in tests

environment-dev.yml, geofileops/util/_sqlite_userdefined.py, tests/test_geofileops_twolayers.py, tests/test_spatialite.py
For some cases erase now doesn't seem to do any erasing at all.
Specifically, if multi-type geometries are subdivided and they result in multi-geometries after subdividing, then (parts of) the multi-geometries are ignored for the difference being applied because spatialite.ST_GeomFromWkb throws them away.
A bug request was filed in the spatialite forum: [bug post](https://groups.google.com/g/spatialite-users/c/GW-Ed0SL81Y/m/yUmh5ZNKBAAJ?utm_medium=email&utm_source=footer)
Note: this fixes a bug in currently unreleased changes... so isn't included in the changelog.
=> Fix erase not giving correct results in some cases

.github/workflows/tests.yml, geofileops/util/_ogr_util.py, tests/test_geofile.py, tests/test_ogr_util.py
- if `cache-environment: true` is specified for action `mamba-org/setup-micromamba@v1`, the environment seems to be cached ad infinitum... so there are never new versions of dependencies -> remove cache.
- Issue is reported here: https://github.com/mamba-org/setup-micromamba/issues/50
- because of the above, gdal 3.7.2 is now installed, and it behaves differently if multiple output_geometry_type's are specified: with combination of "POINT" and "PROMOTE_TO_MULTI" gdal now actually applies "PROMOTE_TO_MULTI", so MULTIPOINTs are  saved in a POINT layer wich gives issues later on: when such a layer is input layer in vecor_translate, an error is thrown.
=> Disable ci environment caching as it seems to cache ad infinitum + support gdal 3.7.2

ci/envs/latest.yml, ci/envs/minimal.yml, ci/envs/readthedocs.yml, setup.py
knn index replaced by knn2 in 5.1, which breaks `join_nearest`
reference #384
=> Fix spatialite version to st 5.1

setup.py
libspatialite doesn't exist as pip package
=> Remove libspatialite as pip requirement

CHANGELOG.md, geofileops/util/_ogr_util.py, tests/test_ogr_util.py
Add information logging via CPL_LOG to the exception so more useful information is available if an error occurs.
When running local, it works to add the information in the CPL_LOG to the exception, but when running CI on github, the CPL_LOG file stays empty :-(.
=> Improve GDAL exception handling

CHANGELOG.md, geofileops/util/_ogr_util.py, tests/test_geofile.py
When `copy_layer` is used on a layer in a .gpkg file contains multi-geometries and explodecollections=True, an error is thrown because gdalTranslate by default tries to preserve the fids.
This is rather an upstream bug, but also possible to fix in geofileops, to this PR does so.
Also opened an upstream issue: https://github.com/OSGeo/gdal/issues/8523
=> Fix error in copy layer with explodecollections on some input files

CHANGELOG.md, docs/reference.rst, geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
`split` is called `identity` in ArcMap, Saga and GeoPandas... and `split` is specific for geofileops, so better to align to the other libraries for convenience (even though I don't understand why it is called "Identity").
=> Rename split to identity

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_ogr.py, geofileops/util/_geoops_sql.py
- a sensible logger name makes logging a lot more consistent and readable, current approach was redundent with `%(pathname)`
- added explicit logging for the steps in multi-step operations like `union` and `symmetric_difference`.
=> Improve logging: use geo operation being executed as `logger name`

CHANGELOG.md, geofileops/util/_geoops_gpd.py, tests/test_geofileops_singlelayer_gpd.py
Output geometry type is sometimes forced to wrong type. As a consequence, when `gfo.dissolve` is ran on an input file with geometry type Polygon, `explodecollections` is `False` and there are `groupby` columns specified, the output of `gfo.dissolve` will be invalid in most cases.
=> Fix dissolve forcing output to wrong geometrytype in some cases

CHANGELOG.md, geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
In some cases identity (and so also union, as it used identity under the hood), is very slow. Not sure what the exact trigger is, but in this case the identity was calculated between two largish input files (2 files of +- 3 GB). Previous test cases focused rather on one big file and one smaller.
This PR introduces 2 changes to solve this:
- the seperate intermediate operations, `intersection` and `erase`, executed seperately took only 50% of the time. This PR changes identity and union so the `intersection` and `erase` are calculated seperately and appended afterwards instead of combining them in one sql query.
- add ST_Intersects filter in the correclated subquery getting the neighbours to erase them. In previous tests the ST_Intersects filter being there or not didn't give a difference, …
=> Speedup identity and union for some files

CHANGELOG.md, geofileops/util/_geoops_sql.py
In #433 a speedup was introduced using spatialite function ST_Subdivide, but while performance testing using large files it became clear the function is flawed: it returns incorrect results in some cases leading to wrong erases. The issue is reported here: https://groups.google.com/g/spatialite-users/c/Pve3dbJj5Ug
This PR replaces this by a pure python implementation, which seems the only working option. in some of the earlier commits in this PR some alternative options are included, but they were all flawed in some way as documented in those commits.
=> Fix to erase speedup introduced in #433

CHANGELOG.md, geofileops/util/_geoops_gpd.py, tests/test_geofileops_singlelayer_gpd.py
In this case an error `input_path doesn't exist: output_xxxx_onborder.gpkg` was raised.
=> Fix dissolve error when pass that isn't last one has 0 polygons in onborder result

CHANGELOG.md, geofileops/util/_general_util.py, geofileops/util/_geoops_gpd.py, tests/test_geofileops_singlelayer_gpd.py
Normally the `groupby` parameter of `dissolve` is case insenitive like other `column` parameters, but it became case sensitive when agg columns was specified.
Fixed.
resolves #457
=> Fix groupby parameter of dissolve becoming case sensitive when agg_columns is also specified

CHANGELOG.md, geofileops/util/_geoops_sql.py, geofileops/util/_sqlite_util.py, tests/test_sqlite_util.py
E.g. `SELECT layer2.naam, 'test' AS naam ... ` raised error `sqlite3.OperationalError: near ":1": syntax error`
Also related to #475, where this could occur for column `spatial_relation`.
=> BUG: Fix error in two layer operations if equal column aliases used based on constant/function result

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
No erasing was done at all in this case...
Same problem for all depending operations: so fixes `erase`, `identity`, `symmetric_difference` and `union`.
Resolves #489
=> BUG: Fix `erase` and depending operations if `subdivide_coords` < 1

CHANGELOG.md, geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
This opens the way to improve performance of `join by location`, because determining the exact relation is relatively expensive.
resolves #475 
related to #502
=> ENH: Remove the column "spatial_relation" from the output of `join_by_location`

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_geofileinfo.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_ogr.py, geofileops/util/_geoops_sql.py, geofileops/util/geofiletypes.csv, tests/test_geofile.py, tests/test_geofileops_singlelayer.py, tests/test_geofileops_singlelayer_gpd.py, tests/test_geofileops_singlelayer_ogr.py, tests/test_geofileops_twolayers.py, tests/test_sqlite_util.py
Now, geofileops always tries to create a spatial index on output files.
For some file formats this isn't relevant though (e.g. .csv), and for some file formats this creates risks for later issues (e.g. the spatial index for shapefile isn't kept up-to-date if the shapefile is updated afterwards).
So, it is most logical just to follow/copy the default behaviour by GDAL.
=> ENH: use the gdal default to create a spatial index on output files or not

.github/workflows/tests.yml, ci/envs/minimal.yml, setup.py, tests/test_geofile.py
Some tests needed to be changed as well as geopandas 1.0 gives some different results when fiona is used:
- when the file has no geometry, a simple DataFrame is returned
- with a shapefile, a datum column becomes a string
This PR changes some tests to account for this + removes fiona from the "minimal" CI env + updates some other dependency versions to avoid having to complicate tests to support the behaviour of old versions of geopandas with fiona.
=> MAINT: update geopandas dependency to support 1.0

CHANGELOG.md, geofileops/util/_geoops_gpd.py
fixes #541 
Problem was the following: because of the tiled processing in `dissolve`, geometries crossing the boundaries of the tiles are in two partial result files. The duplicates in attribute results are solved because the column values are saved as json strings in the partial result files, and duplicate json stings are removed before calculating the aggregate attribute values. However, because `set` was used to avoid duplicate columns/keys being stored in the json strings, the order of keys was not fixed, and when the order was different, the duplicates could not be correctly removed.
=> BUG: fix `dissolve` with `agg_columns` gives sometimes wrong aggregation results

geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
Just like on MacOS, `test_symmetric_difference` and `test_union` now also give small differences for the 4326 tests on linux.
=> TST: fix tests on linux

geofileops/util/_geoops_sql.py, tests/test_geofileops_twolayers.py
Subdivide them up-front, otherwise the subdivide happens multiple times: in `intersection` and both `difference` operations.
closes #591
=> ENH: only apply subdivide once on each input layer in union

.github/workflows/tests.yml, .pre-commit-config.yaml
Using the action is in maintenance only mode, and the advice is to use pre-commit-ci instead: https://github.com/pre-commit/action
=> CI: use pre-commit-ci instead of github action

geofileops/_compat.py, geofileops/util/_ogr_util.py, tests/test_geofileops_twolayers.py
Changes:
- don't use arrow for `gdal.VectorTranslate` for all GDAL versions < 3.11
- remove redundant cast to datetime in test that gives an error for gdal > 3.10.0
=> ENH: support GDAL 3.10.1

CHANGELOG.md, geofileops/util/_geoops_sql.py, tests/test_geoops_sql.py
Apparently very large linestring layer also become very slow for intersection,... so subdividing those is necessary as well.
=> ENH: enable subdividing of linestring layers as well

.github/workflows/tests.yml, ci/envs/nightly-deps.yml, environment-dev.yml, geofileops/_compat.py
Add CI config to test on the gdal "nightly" master version.
GDAL will be installed from the gdal-master conda channel: https://anaconda.org/gdal-master/libgdal-core/files
Activating gdal nightly CI triggered this:
=> CI: add nightly-deps environment to test on

CHANGELOG.md, geofileops/util/_sqlite_util.py
SQLite transactions using sqlite3 in python don't work very well...
Apparently, you need to explicitly call "BEGIN TRANSACTION;" to get a proper transaction.
reference #621
=> ENH: use explicit transactions to speed up on windows

CHANGELOG.md, geofileops/_compat.py
There doesn't seem to be a lot of use that this is being tested in every worker process as well...
=> ENH: only check spatialite versions in main process

geofileops/fileops.py, tests/test_helper.py
Fix a concurrency issue when test files are being created: prepare test files being created in a temp file and then move them so they are only visible to other processes once they are completely ready.
=> TST: run CI tests in parallel - fix concurrency issue

geofileops/_compat.py, geofileops/helpers/_configoptions_helper.py, geofileops/helpers/_general_helper.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, tests/test_general_helper.py, tests/test_geofileops_singlelayer.py, tests/test_geofileops_twolayers.py, tests/test_geoops_dissolve.py
Issue introduced in #627 (unreleased change)
For performance reasons, by default multithreading is used on windows for small files... but because the tests use small files... multiprocessing is not covered in the tests.
In this PR:
- Make multithreading versus multiprocessing configurable so multiprocessing is properly covered in the CI tests
- Fix the issue
=> BUG: fix error with multiprocessing on windows

CHANGELOG.md, geofileops/util/_geoops_gpd.py
Fix `dissolve` with `agg_columns` used on sqlite 3.49.1. throwing error: `no such column: "$" - should this be a string literal in single-quotes?`
Apparently 3.49.1 has become more strict on single versus double quotes used in SQL for json functions.
=> BUG: fix `dissolve` with `agg_columns` on sqlite 3.49.1

.github/workflows/tests_installed.yml
=> CI: pin geofileops 0.9.1 to build 3 on tests_installed to avoid old version of sqlite being installed

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_ogr_util.py, tests/test_geofile.py, tests/test_ogr_util.py
If adding the column succeeds but the update fails, the output files is in a state that is not ideal: when the `add_column` is ran again, the column won't be "fixed". It would be better that this is transactional: if the update fails, the add should be rolled back well.
This PR adds using transactions for this case.
Mind: transactions are not supported for all file types! E.g. 
- for .gpkg this will work fine.
- for .shp the column will still stay added as transactions are not supported.
=> ENH: in add_column, don't add column if update expression is invalid

ci/envs/latest-fiona.yml, ci/envs/latest.yml, ci/envs/readthedocs.yml, environment-dev.yml, geofileops/__init__.py, geofileops/_compat.py, geofileops/fileops.py, setup.py
make pyogrio 0.7 the minimal version
and:
- remove code that becomes obsolete due to this...
- move the pre-flight check code for the spatialite versions to __init__.py because it gave circular references in _compat.py
=> MAINT: make pyogrio 0.7 the minimal version

CHANGELOG.md, geofileops/helpers/_general_helper.py, geofileops/util/_processing_util.py, tests/test_general_helper.py, tests/test_geofileops_singlelayer.py, tests/test_geoops_dissolve.py, tests/two_layer_operations/test_geofileops_twolayers.py
Use "forkserver" to create worker processes on linux.
This solves the following deprecationwarning: `This process (pid=2361) is multi-threaded, use of fork() may lead to deadlocks in the child.`
"forkserver" will become the default on [python 3.14](https://docs.python.org/3.14/whatsnew/3.14.html#concurrent-futures).
Note: this does have a significant performance impact in some use cases. E.g. running the tests (a lot of operations on small files that are forced to run in 2 processes) took:
- 1.5 minutes using fork
- 5.5 minutes using forkserver
- 7.5 minutes using spawn
- 1.5 minutes using threads (which is now the case: if input files < 100 rows)
=> ENH: use forkserver to create worker processes on linux

CHANGELOG.md, docs/faq.rst, geofileops/fileops.py, pyproject.toml
Add a warning when the GFO_IO_ENGINE configuration option is used with engine "fiona" that this is deprecated and
will be removed/ignored in a future version.
=> DEPR: deprecate the GFO_IO_ENGINE configuration option

CHANGELOG.md, geofileops/geoops.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, tests/single_layer_operations/test_geofileops_singlelayer.py, tests/single_layer_operations/test_geoops_dissolve.py, tests/two_layer_operations/test_geofileops_twolayers.py
The idea is that if the output file exists already and `force=False`, that no processing is done and hence dealing with that is fast.
However, if the input geopackages don't have a filled out gpkg_ogr_contents.featurecount table/column, in many cases this seems to take quite some time anyway.
This PR moves the output_exists check forward on many places to speed this up. Disadvantage is that most input parameter checks are now afterwards...
reference #695
=> BUG: on some input files spatial operations take significant time even though output exists

CHANGELOG.md, geofileops/util/_geofileinfo.py, tests/general_file_layer_operations/test_geofile.py, tests/util/test_geofileinfo.py
E.g. when using a .zip file as source file with /vsizip/, `copy_file` gives an error while this should work.
Also improves error messages in some cases.
=> BUG: fix copy_file for some special vsi cases

CHANGELOG.md, geofileops/helpers/_configoptions_helper.py, tests/helpers/test_configoptions_helper.py
For some config options invalid values were just ignored... Now, a ValueError will be raised.
=> ENH: add checks on invalid values in `ConfigOptions`

CHANGELOG.md, geofileops/util/_ogr_util.py
When running large analysis, recently (rare) random crashes started occuring, without any error reporting at all.
It looks like it is linked with arrow being used in `gdal.VectorTranslate`. Arrow was already disabled for GDAL < 3.11, this PR disables it for all GDAL versions (till this is cleared out) by setting GDAL configuration option `OGR2OGR_USE_ARROW_API=NO`.
=> [backport] BUG: disable arrow in gdal.VectorTranslate to avoid random crashes (#714)

CHANGELOG.md, geofileops/util/_general_util.py, tests/util/test_general_util.py
When `{ key: None }` is passed as environment variable to be set this results in the environment variable being set to `"None"`. The environment variable should be removed though...
=> [backport] Fix handling `None` values for environment variables in `gfo.TempEnv` (#710)

CHANGELOG.md, benchmark/benchmark_geofileops.py, benchmark/benchmarks/benchmarks_geofileops.py, geofileops/_compat.py, geofileops/fileops.py, geofileops/helpers/_configoptions_helper.py, geofileops/util/_geoops_gpd.py, geofileops/util/_geoops_sql.py, geofileops/util/_geoseries_util.py, geofileops/util/_sqlite_util.py, tests/general_file_layer_operations/test_geofile.py, tests/single_layer_operations/test_geofileops_singlelayer.py, tests/util/test_sqlite_util.py
Improve performance of `copy_layer` for appends from gpkg to gpkg. Because this is used to merge the results of all batches in all operations, this improves performance significantly for (almost) all operations when processing large files.
Can be disabled by defining configuration option `GFO_COPY_LAYER_SQLITE_DIRECT=0`.
Resolves #732
=> PERF: improve performance of gpkg to gpkg appends

CHANGELOG.md, geofileops/fileops.py, geofileops/util/_ogr_util.py, tests/general_file_layer_operations/test_geofile.py, tests/util/test_ogr_util.py
Now it does the default behaviour of gdal.VectorTranslate, which is apparently to just take the first layer encountered.
=> BUG: copy_layer should give an error if src_layer is not specified for multi-layer src files

CHANGELOG.md, ci/envs/latest-fiona.yml, ci/envs/latest.yml, ci/envs/minimal.yml, ci/envs/readthedocs.yml, geofileops/_compat.py, geofileops/geoops.py, geofileops/util/_geoops_sql.py, tests/single_layer_operations/test_geofileops_singlelayer.py, tests/test_spatialite.py, tests/two_layer_operations/test_geofileops_twolayers.py
Support can be dropped:
- is old enough now (5.1 was released 2023-04-08
- newer versions of GDAL aren't compatible with it anymore either
- nice code and test cleanup/simplification
=> MAINT: drop support for libspatialite 5.0

geofileops/util/_ogr_util.py, tests/single_layer_operations/test_geofileops_singlelayer_ogr.py
Use parameters to VectorTranslate instead of args where the are available in GDAL >= 3.8.
Remark:
- when adding an extra test for `clip_by_geometry` an issue was found, reported here: https://github.com/OSGeo/gdal/issues/13178
=> ENH: small code cleanup in ogr_util
